name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults: 
      run: 
        working-directory: ./flutterapp/app/nathan_johnson_flutterapp/
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
  deploy:   
    defaults: 
      run: 
        working-directory: ./flutterapp/app/nathan_johnson_flutterapp/
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./web
           enable_jekyll: true

#In working through this, I used a basic Dart workflow/action templete 
#and also used code from https://github.com/marketplace/actions/flutter-action to acheive functionality. 
#I had to specify the working directory in order to make the flutter commands work, as they were running at the root of my repo.
