name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
       build:
         runs-on: ubuntu-latest
         steps:
          - uses: actions/checkout@v4
          - uses: subosito/flutter-action@v2
            with:
              channel: 'stable'
          - run: cd flutterapp/app/nathan_johnson_flutterapp/test
          - run: flutter doctor
       #   - run: flutter pub get
          - run: flutter test widget_test.dart
          - run: flutter build web
