name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - working-directory: flutterapp/app/nathan_johnson_flutterapp
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor
      #- run: flutter pub get
      - run: flutter test
      - run: flutter build web
