name: Flutter Deploy
permissions: write-all
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    defaults: 
      run: 
        working-directory: ./flutterapp/app/application
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: atlas-77/Flutter@v1
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutterapp/app/application/build/web/
          enable_jekyll: true
           
           
